//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpreadsheetEditorDemo.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpreadsheetEditorDemo.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string DEMOSCOMMONCODE_ABOUT {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has invalid format..
        /// </summary>
        internal static string DEMOSCOMMONCODE_ARG0_HAS_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ARG0_HAS_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the panel if current color must be changed..
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_ON_THE_PANEL_IF_CURRENT_COLOR_MUST_BE_CHANGED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_ON_THE_PANEL_IF_CURRENT_COLOR_MUST_BE_CHANGE" +
                        "D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button if the current color must be changed..
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_THE_BUTTON_IF_THE_CURRENT_COLOR_MUST_BE_CHANGED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_THE_BUTTON_IF_THE_CURRENT_COLOR_MUST_BE_CHAN" +
                        "GED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button if the current color must be set to the default color..
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_THE_BUTTON_IF_THE_CURRENT_COLOR_MUST_BE_SET_TO_THE_DEFAULT_COLOR {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_THE_BUTTON_IF_THE_CURRENT_COLOR_MUST_BE_SET_" +
                        "TO_THE_DEFAULT_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click on the panel if the current color must be changed..
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_DOUBLE_CLICK_ON_THE_PANEL_IF_THE_CURRENT_COLOR_MUST_BE_CHANGED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_DOUBLE_CLICK_ON_THE_PANEL_IF_THE_CURRENT_COLOR_MUS" +
                        "T_BE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Name.
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_VALUE_NAME {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_VALUE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_ERROR {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_ERROR_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ERROR_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_ERROR_ALT2 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ERROR_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_ERROR_ALT3 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ERROR_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Finished ({0})..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING__FINISHED_ARG0 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING__FINISHED_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Result.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_AUTHORIZATION_RESULT {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_AUTHORIZATION_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized as: &apos;{0}&apos;.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_AUTHORIZED_AS_ARG0 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_AUTHORIZED_AS_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CANCEL {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CANCELED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CANCELED_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CANCELED_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CLOSE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndpi.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_NDPI {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_NDPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CUSTOM {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CUSTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CUSTOM_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CUSTOM_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ERROR {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ERROR_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ERROR_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_FINISHED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_PASSWORD {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password - {0}.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_PASSWORD_ARG0 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_PASSWORD_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; password is incorrect..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_THE_ARG0_PASSWORD_IS_INCORRECT {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_THE_ARG0_PASSWORD_IS_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_UNDEFINED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_UNDEFINED_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_UNDEFINED_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_UNDEFINED_ALT2 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_UNDEFINED_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_UNDEFINED_ALT3 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_UNDEFINED_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be null..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_VALUE_CAN_NOT_BE_NULL {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_VALUE_CAN_NOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string DEMOSCOMMONCODE_INFORMATION {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception: {0}.
        /// </summary>
        internal static string DEMOSCOMMONCODE_INNER_EXCEPTION_ARG0 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_INNER_EXCEPTION_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; was not found..
        /// </summary>
        internal static string DEMOSCOMMONCODE_RESOURCE_ARG0_WAS_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_RESOURCE_ARG0_WAS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string DEMOSCOMMONCODE_WARNING {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Stacked Area.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_100_STACKED_AREA {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_100_STACKED_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Stacked Bar.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_100_STACKED_BAR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_100_STACKED_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Stacked Column.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_100_STACKED_COLUMN {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_100_STACKED_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Stacked Curved Line.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_100_STACKED_CURVED_LINE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_100_STACKED_CURVED_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Stacked Curved Line with Markers.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_100_STACKED_CURVED_LINE_WITH_MARKERS {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_100_STACKED_CURVED_LINE_WITH_MARKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Stacked Line.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_100_STACKED_LINE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_100_STACKED_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Stacked Line with Markers.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_100_STACKED_LINE_WITH_MARKERS {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_100_STACKED_LINE_WITH_MARKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D 100% Stacked Area.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_100_STACKED_AREA {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_100_STACKED_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D 100% Stacked Bar.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_100_STACKED_BAR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_100_STACKED_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D 100% Stacked Column.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_100_STACKED_COLUMN {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_100_STACKED_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D Area.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_AREA {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D Bubble.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_BUBBLE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_BUBBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D Clustered Bar.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_CLUSTERED_BAR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_CLUSTERED_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D Clustered Column.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_CLUSTERED_COLUMN {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_CLUSTERED_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D Column.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_COLUMN {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D Line.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_LINE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D Pie.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_PIE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_PIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D Pie (Explosion).
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_PIE_EXPLOSION {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_PIE_EXPLOSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D Stacked Column.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_STACKED_COLUMN {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_STACKED_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-D Surface.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_3D_SURFACE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_3D_SURFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cell reference cannot be evaluated..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_A_CELL_REFERENCE_CANNOT_BE_EVALUATED {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_A_CELL_REFERENCE_CANNOT_BE_EVALUATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cell reference cannot be evaluated because the value for the cell has not been retrieved or calculated..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_A_CELL_REFERENCE_CANNOT_BE_EVALUATED_BECAUSE_THE_VALUE_FOR_THE_CELL_HAS_NOT_BEEN_RETRIEVED_OR_CALCULATED {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_A_CELL_REFERENCE_CANNOT_BE_EVALUATED_BECAUSE_THE_VALUE_FOR_" +
                        "THE_CELL_HAS_NOT_BEEN_RETRIEVED_OR_CALCULATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A designated value is not available..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_A_DESIGNATED_VALUE_IS_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_A_DESIGNATED_VALUE_IS_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ADD_COMMENT {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ADD_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Defined Name.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ADD_DEFINED_NAME {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ADD_DEFINED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hyperlink.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ADD_HYPERLINK {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ADD_HYPERLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add hyperlink.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ADD_HYPERLINK_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ADD_HYPERLINK_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add hyperlink.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ADD_HYPERLINK_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ADD_HYPERLINK_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add hyperlink.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ADD_HYPERLINK_ALT3 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ADD_HYPERLINK_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ALL {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ALL_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ALL_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ALL_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ALL_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ALL_ALT3 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ALL_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All checkboxes cannot be disabled..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ALL_CHECKBOXES_CANNOT_BE_DISABLED {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ALL_CHECKBOXES_CANNOT_BE_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An argument to a function has a compatible type but has a value that is outside the domain over which that function is defined..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_AN_ARGUMENT_TO_A_FUNCTION_HAS_A_COMPATIBLE_TYPE_BUT_HAS_A_VALUE_THAT_IS_OUTSIDE_THE_DOMAIN_OVER_WHICH_THAT_FUNCTION_IS_DEFINED {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_AN_ARGUMENT_TO_A_FUNCTION_HAS_A_COMPATIBLE_TYPE_BUT_HAS_A_V" +
                        "ALUE_THAT_IS_OUTSIDE_THE_DOMAIN_OVER_WHICH_THAT_FUNCTION_IS_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incompatible type argument is passed to a function, or an incompatible type operand is used with an operator..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_AN_INCOMPATIBLE_TYPE_ARGUMENT_IS_PASSED_TO_A_FUNCTION_OR_AN_INCOMPATIBLE_TYPE_OPERAND_IS_USED_WITH_AN_OPERATOR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_AN_INCOMPATIBLE_TYPE_ARGUMENT_IS_PASSED_TO_A_FUNCTION_OR_AN" +
                        "_INCOMPATIBLE_TYPE_OPERAND_IS_USED_WITH_AN_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any number (including zero) or any error code is divided by zero..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ANY_NUMBER_INCLUDING_ZERO_OR_ANY_ERROR_CODE_IS_DIVIDED_BY_ZERO {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ANY_NUMBER_INCLUDING_ZERO_OR_ANY_ERROR_CODE_IS_DIVIDED_BY_Z" +
                        "ERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_AREA {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_AREA_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_AREA_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cells found..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ARG0_CELLS_FOUND {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ARG0_CELLS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ARG0_MUST_BE_BETWEEN_ARG1_AND_ARG2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ARG0_MUST_BE_BETWEEN_ARG1_AND_ARG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; replacements are made..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ARG0_REPLACEMENTS_ARE_MADE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ARG0_REPLACEMENTS_ARE_MADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires an integer or decimal number..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ARG0_REQUIRES_AN_INTEGER_OR_DECIMAL_NUMBER {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ARG0_REQUIRES_AN_INTEGER_OR_DECIMAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BAR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BOLD {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BOLD_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BOLD_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BOLD_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BOLD_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BOLD_ALT3 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BOLD_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BOLD_ALT4 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BOLD_ALT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BOLD_ITALIC {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BOLD_ITALIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BOLD_ITALIC_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BOLD_ITALIC_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BOLD_ITALIC_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BOLD_ITALIC_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BOLD_ITALIC_ALT3 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BOLD_ITALIC_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BOLD_ITALIC_ALT4 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BOLD_ITALIC_ALT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BOLD_ITALIC_ALT5 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BOLD_ITALIC_ALT5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_BUBBLE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_BUBBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a match..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CANNOT_FIND_A_MATCH {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CANNOT_FIND_A_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell {0} with formula &apos;={1}&apos; calculation error: {2}.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CELL_ARG0_WITH_FORMULA_ARG1_CALCULATION_ERROR_ARG2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CELL_ARG0_WITH_FORMULA_ARG1_CALCULATION_ERROR_ARG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell reference is invalid..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CELL_REFERENCE_IS_INVALID {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CELL_REFERENCE_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart ({0}).
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CHART_ARG0 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CHART_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clustered Bar.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CLUSTERED_BAR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CLUSTERED_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clustered Column.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CLUSTERED_COLUMN {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CLUSTERED_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_COLUMN {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column width.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_COLUMN_WIDTH {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_COLUMN_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column width.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_COLUMN_WIDTH_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_COLUMN_WIDTH_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column width must be an integer or decimal number..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_COLUMN_WIDTH_MUST_BE_AN_INTEGER_OR_DECIMAL_NUMBER {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_COLUMN_WIDTH_MUST_BE_AN_INTEGER_OR_DECIMAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column width must be greater than or equal 0..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_COLUMN_WIDTH_MUST_BE_GREATER_THAN_OR_EQUAL_0 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_COLUMN_WIDTH_MUST_BE_GREATER_THAN_OR_EQUAL_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column width must be less than or equal {0}..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_COLUMN_WIDTH_MUST_BE_LESS_THAN_OR_EQUAL_ARG0 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_COLUMN_WIDTH_MUST_BE_LESS_THAN_OR_EQUAL_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert CSV to XLSX.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CONVERT_CSV_TO_XLSX {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CONVERT_CSV_TO_XLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert TSV to XLSX.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CONVERT_TSV_TO_XLSX {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CONVERT_TSV_TO_XLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert XLS to XLSX.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CONVERT_XLS_TO_XLSX {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CONVERT_XLS_TO_XLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find anything to replace..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_COULD_NOT_FIND_ANYTHING_TO_REPLACE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_COULD_NOT_FIND_ANYTHING_TO_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csv.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CSV {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current workbook is changed. Do you want to save changes?.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CURRENT_WORKBOOK_IS_CHANGED_DO_YOU_WANT_TO_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CURRENT_WORKBOOK_IS_CHANGED_DO_YOU_WANT_TO_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Line.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CURVED_LINE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CURVED_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curved Line with Markers.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CURVED_LINE_WITH_MARKERS {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CURVED_LINE_WITH_MARKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ALT3 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ITALIC {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ITALIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ITALIC_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ITALIC_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ITALIC_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ITALIC_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ITALIC_ALT3 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ITALIC_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ITALIC_ALT4 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_BOLD_ITALIC_ALT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size must be an integer or decimal number..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_FONT_SIZE_MUST_BE_AN_INTEGER_OR_DECIMAL_NUMBER {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_FONT_SIZE_MUST_BE_AN_INTEGER_OR_DECIMAL_NUMB" +
                        "ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font style with name &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_FONT_STYLE_WITH_NAME_ARG0_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_FONT_STYLE_WITH_NAME_ARG0_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_ITALIC {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_ITALIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_ITALIC_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_ITALIC_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_ITALIC_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_ITALIC_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_ITALIC_ALT3 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_ITALIC_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_REGULAR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_REGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_REGULAR_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_REGULAR_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_REGULAR_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_CUSTOMCONTROLS_REGULAR_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data point appearance.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_DATA_POINT_APPEARANCE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_DATA_POINT_APPEARANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Point {0}.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_DATA_POINT_ARG0 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_DATA_POINT_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt XLSX.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_DECRYPT_XLSX {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_DECRYPT_XLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default column width.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_DEFAULT_COLUMN_WIDTH {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_DEFAULT_COLUMN_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default row height.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_DEFAULT_ROW_HEIGHT {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_DEFAULT_ROW_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined name is not selected..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_DEFINED_NAME_IS_NOT_SELECTED {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_DEFINED_NAME_IS_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doughnut.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_DOUGHNUT {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_DOUGHNUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_EDIT {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_EDIT_COMMENT {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_EDIT_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_EDIT_COMMENT_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_EDIT_COMMENT_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_EDIT_COMMENT_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_EDIT_COMMENT_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ERROR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ERROR_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ERROR_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ERROR_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ERROR_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ERROR_ALT3 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ERROR_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export document.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_EXPORT_DOCUMENT {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_EXPORT_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export document.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_EXPORT_DOCUMENT_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_EXPORT_DOCUMENT_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External error..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_EXTERNAL_ERROR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_EXTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Radar.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_FILLED_RADAR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_FILLED_RADAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size must be an integer or decimal number..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_FONT_SIZE_MUST_BE_AN_INTEGER_OR_DECIMAL_NUMBER {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_FONT_SIZE_MUST_BE_AN_INTEGER_OR_DECIMAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font style with name &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_FONT_STYLE_WITH_NAME_ARG0_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_FONT_STYLE_WITH_NAME_ARG0_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Syntax Error.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_FORMULA_SYNTAX_ERROR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_FORMULA_SYNTAX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0} pages.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_FROM_ARG0_PAGES {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_FROM_ARG0_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_HELP {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_HELP_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_HELP_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_HELP_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_HELP_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-Low-Close.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_HIGHLOWCLOSE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_HIGHLOWCLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Chart.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_INSERT_CHART {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_INSERT_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ITALIC {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ITALIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ITALIC_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ITALIC_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ITALIC_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ITALIC_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ITALIC_ALT3 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ITALIC_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ITALIC_ALT4 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ITALIC_ALT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line with Markers.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_LINE_WITH_MARKERS {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_LINE_WITH_MARKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link: .
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_LINK {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_LOADING {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like a name is used but no such name has been defined..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_LOOKS_LIKE_A_NAME_IS_USED_BUT_NO_SUCH_NAME_HAS_BEEN_DEFINED {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_LOOKS_LIKE_A_NAME_IS_USED_BUT_NO_SUCH_NAME_HAS_BEEN_DEFINED" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is not defined..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_NAME_IS_NOT_DEFINED {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_NAME_IS_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Workbook.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_NEW_WORKBOOK {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_NEW_WORKBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_NO_ERROR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_NO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open-High-Low-Close.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_OPENHIGHLOWCLOSE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_OPENHIGHLOWCLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_PIE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_PIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_PIE_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_PIE_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie (Explosion).
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_PIE_EXPLOSION {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_PIE_EXPLOSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_PROCESSING {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_RADAR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_RADAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_RADAR_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_RADAR_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar with Markers.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_RADAR_WITH_MARKERS {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_RADAR_WITH_MARKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_READY {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_RED {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_RED_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_RED_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_RED_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_RED_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference is not valid..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_REFERENCE_IS_NOT_VALID {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_REFERENCE_IS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_REGULAR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_REGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_REGULAR_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_REGULAR_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_REGULAR_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_REGULAR_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_REGULAR_ALT3 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_REGULAR_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Worksheet.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_REMOVE_WORKSHEET {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_REMOVE_WORKSHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove worksheet &apos;{0}&apos;?.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_REMOVE_WORKSHEET_ARG0 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_REMOVE_WORKSHEET_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_REPLACE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_REPLACE_ALL {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_REPLACE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_REPLACE_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_REPLACE_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_REPLACE_ALT2 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_REPLACE_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row height.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ROW_HEIGHT {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ROW_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row height.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ROW_HEIGHT_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ROW_HEIGHT_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row height must be an integer or decimal number..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ROW_HEIGHT_MUST_BE_AN_INTEGER_OR_DECIMAL_NUMBER {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ROW_HEIGHT_MUST_BE_AN_INTEGER_OR_DECIMAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row height must be greater than or equal 0..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ROW_HEIGHT_MUST_BE_GREATER_THAN_OR_EQUAL_0 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ROW_HEIGHT_MUST_BE_GREATER_THAN_OR_EQUAL_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row height must be less than or equal {0}..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_ROW_HEIGHT_MUST_BE_LESS_THAN_OR_EQUAL_ARG0 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_ROW_HEIGHT_MUST_BE_LESS_THAN_OR_EQUAL_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_SCATTER {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_SCATTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_SCATTER_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_SCATTER_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter with Smooth Lines.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_SCATTER_WITH_SMOOTH_LINES {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_SCATTER_WITH_SMOOTH_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter with Smooth Lines and Markers.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_SCATTER_WITH_SMOOTH_LINES_AND_MARKERS {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_SCATTER_WITH_SMOOTH_LINES_AND_MARKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter with Straight Lines.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_SCATTER_WITH_STRAIGHT_LINES {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_SCATTER_WITH_STRAIGHT_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter with Straight Lines and Markers.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_SCATTER_WITH_STRAIGHT_LINES_AND_MARKERS {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_SCATTER_WITH_STRAIGHT_LINES_AND_MARKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series appearance.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_SERIES_APPEARANCE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_SERIES_APPEARANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series {0}.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_SERIES_ARG0 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_SERIES_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set chart properties.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_SET_CHART_PROPERTIES {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_SET_CHART_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Area.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_STACKED_AREA {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_STACKED_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Area.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_STACKED_AREA_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_STACKED_AREA_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Bar.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_STACKED_BAR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_STACKED_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Bar.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_STACKED_BAR_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_STACKED_BAR_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Column.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_STACKED_COLUMN {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_STACKED_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Curved Line.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_STACKED_CURVED_LINE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_STACKED_CURVED_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Curved Line with Markers.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_STACKED_CURVED_LINE_WITH_MARKERS {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_STACKED_CURVED_LINE_WITH_MARKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Line.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_STACKED_LINE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_STACKED_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Line with Markers.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_STACKED_LINE_WITH_MARKERS {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_STACKED_LINE_WITH_MARKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_STOCK {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text &apos;{0}&apos; is not found..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_TEXT_ARG0_IS_NOT_FOUND {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_TEXT_ARG0_IS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text &apos;{0}&apos; is not found..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_TEXT_ARG0_IS_NOT_FOUND_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_TEXT_ARG0_IS_NOT_FOUND_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drawing name cannot be empty..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_THE_DRAWING_NAME_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_THE_DRAWING_NAME_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loaded file is CSV file. To open CSV file application needs to convert CSV file to the XLSX file. Do you want to create XLSX file from CSV file?.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_THE_LOADED_FILE_IS_CSV_FILE_TO_OPEN_CSV_FILE_APPLICATION_NEEDS_TO_CONVERT_CSV_FILE_TO_THE_XLSX_FILE_DO_YOU_WANT_TO_CREATE_XLSX_FILE_FROM_CSV_FILE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_THE_LOADED_FILE_IS_CSV_FILE_TO_OPEN_CSV_FILE_APPLICATION_NE" +
                        "EDS_TO_CONVERT_CSV_FILE_TO_THE_XLSX_FILE_DO_YOU_WANT_TO_CREATE_XLSX_FILE_FROM_CS" +
                        "V_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loaded file is secured XLSX file. To open secured file application needs to decrypt XLSX file. Do you want to create decrypted XLSX file?.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_THE_LOADED_FILE_IS_SECURED_XLSX_FILE_TO_OPEN_SECURED_FILE_APPLICATION_NEEDS_TO_DECRYPT_XLSX_FILE_DO_YOU_WANT_TO_CREATE_DECRYPTED_XLSX_FILE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_THE_LOADED_FILE_IS_SECURED_XLSX_FILE_TO_OPEN_SECURED_FILE_A" +
                        "PPLICATION_NEEDS_TO_DECRYPT_XLSX_FILE_DO_YOU_WANT_TO_CREATE_DECRYPTED_XLSX_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loaded file is TSV file. To open TSV file application needs to convert TSV file to the XLSX file. Do you want to create XLSX file from TSV file?.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_THE_LOADED_FILE_IS_TSV_FILE_TO_OPEN_TSV_FILE_APPLICATION_NEEDS_TO_CONVERT_TSV_FILE_TO_THE_XLSX_FILE_DO_YOU_WANT_TO_CREATE_XLSX_FILE_FROM_TSV_FILE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_THE_LOADED_FILE_IS_TSV_FILE_TO_OPEN_TSV_FILE_APPLICATION_NE" +
                        "EDS_TO_CONVERT_TSV_FILE_TO_THE_XLSX_FILE_DO_YOU_WANT_TO_CREATE_XLSX_FILE_FROM_TS" +
                        "V_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loaded file is XLS file. To open XLS file application needs to convert XLS file to the XLSX file. Do you want to create XLSX file from XLS file?.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_THE_LOADED_FILE_IS_XLS_FILE_TO_OPEN_XLS_FILE_APPLICATION_NEEDS_TO_CONVERT_XLS_FILE_TO_THE_XLSX_FILE_DO_YOU_WANT_TO_CREATE_XLSX_FILE_FROM_XLS_FILE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_THE_LOADED_FILE_IS_XLS_FILE_TO_OPEN_XLS_FILE_APPLICATION_NE" +
                        "EDS_TO_CONVERT_XLS_FILE_TO_THE_XLSX_FILE_DO_YOU_WANT_TO_CREATE_XLSX_FILE_FROM_XL" +
                        "S_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file type does not support workbooks that contain multiple sheets.
        ///To save only the active sheet, click OK.
        ///To save all sheets, save them individually using a different file name for each, or choose a file type that supports multiple sheets..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_THE_SELECTED_FILE_TYPE_DOES_NOT_SUPPORT_WORKBOOKS_THAT_CONTAIN_MULTIPLE_SHEETSRNTO_SAVE_ONLY_THE_ACTIVE_SHEET_CLICK_OKRNTO_SAVE_ALL_SHEETS_SAVE_THEM_INDIVIDUALLY_USING_A_DIFFERENT_FILE_NAME_FOR_EACH_OR_CHOOSE_A_FILE_TYPE_THAT_SUPPORTS_MULTIPLE_SHEETS {
            get {
                return ResourceManager.GetString(@"SPREADSHEETEDITORDEMO_THE_SELECTED_FILE_TYPE_DOES_NOT_SUPPORT_WORKBOOKS_THAT_CONTAIN_MULTIPLE_SHEETSRNTO_SAVE_ONLY_THE_ACTIVE_SHEET_CLICK_OKRNTO_SAVE_ALL_SHEETS_SAVE_THEM_INDIVIDUALLY_USING_A_DIFFERENT_FILE_NAME_FOR_EACH_OR_CHOOSE_A_FILE_TYPE_THAT_SUPPORTS_MULTIPLE_SHEETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI is not valid: .
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_THE_URI_IS_NOT_VALID {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_THE_URI_IS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tsv.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_TSV {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_TSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tsv.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_TSV_ALT1 {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_TSV_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |TSV files|*.tsv|CSV files|*.csv.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_TSV_FILESTSVCSV_FILESCSV {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_TSV_FILESTSVCSV_FILESCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two areas are required to intersect but do not..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_TWO_AREAS_ARE_REQUIRED_TO_INTERSECT_BUT_DO_NOT {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_TWO_AREAS_ARE_REQUIRED_TO_INTERSECT_BUT_DO_NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_UNEXPECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VintaSoft Spreadsheet Editor Demo v.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_VINTASOFT_SPREADSHEET_EDITOR_DEMO_V {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_VINTASOFT_SPREADSHEET_EDITOR_DEMO_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframe 3-D Surface.
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_WIREFRAME_3D_SURFACE {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_WIREFRAME_3D_SURFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet name cannot contains more than 40 symbols..
        /// </summary>
        internal static string SPREADSHEETEDITORDEMO_WORKSHEET_NAME_CANNOT_CONTAINS_MORE_THAN_40_SYMBOLS {
            get {
                return ResourceManager.GetString("SPREADSHEETEDITORDEMO_WORKSHEET_NAME_CANNOT_CONTAINS_MORE_THAN_40_SYMBOLS", resourceCulture);
            }
        }
    }
}
